version: '3'
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: wr2net/laravel
    container_name: api
    working_dir: /var/www
    volumes:
      - ./api:/var/www
    tty: true
    ports:
      - "8000:8000"
    networks:
      - wr2net
    depends_on:
      - db
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - wr2net
networks:
  wr2net:
    driver: bridge
