version: '3.9'

services:
  zip-db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    container_name: zip-db
    restart: always
    tty: true
    volumes:
      - "./mysql/:/var/lib/mysql"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: ''
      MYSQL_RANDOM_ROOT_PASSWORD: ''
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'zipcode'
    ports:
      - "3306:3306"

  zip-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: zip-api
    working_dir: /var/www
    tty: true
    ports:
      - "8000:8000"
    volumes:
      - "./api:/var/www"
    depends_on:
      - zip-db