version: '3'

services:

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/var/www
    entrypoint: composer install && php artisan migrate && php artisan serrve
    image: wr2net/laravel
    container_name: api
    tty: true
    ports:
      - "8000:8000"
    networks:
      - wr2net
    depends_on:
      - db
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - wr2net

networks:
  wr2net:
    name: wr2net
    driver: bridge